- datacommons/datacommons.py
- datacommons/test/datacommons_test.py
When a property contains multiple values, this gets expanded into multiple rows in the Pandas dataframe.
> Pandas dataframes returned by the query API are now singleton cells

- datacommons_pandas/populations.py
Closes #179 
The command that was broken was `gcloud meta list-files-for-upload` at the root of the repo. I verified that this is the only broken symlink in the repo by running the command after the change. As expected, no errors were raised.
> Remove broken symlink

- .gitignore
This is a housekeeping PR which adds the folder structure we plan to implement, based on the design document.
The folders are empty (other than `__init__` files).
We decided to put everything inside `/datacommons_client` while the DC team decides how they want to structure things with the different packages and libraries. The structure could always be refactored in the future, but this will allow us to develop in a relatively clean environment without deleting or moving things around.
> Add Initial Folder Structure for Data Commons Client

- datacommons_client/models/node.py
- datacommons_client/models/observation.py
- datacommons_client/models/resolve.py
- datacommons_client/models/sparql.py
- datacommons_client/tests/models/test_node_models.py
- datacommons_client/tests/models/test_observation_models.py
- datacommons_client/tests/models/test_resolve_models.py
- datacommons_client/tests/models/test_sparql_models.py
**Note:**
Previous PR in the stack: #202
Next PR in the stack #204
---
This PR implements dataclasses to model API responses from all endpoints. These data classes represent various entities in the Data Commons knowledge graph. Dan's comments on the design document provide more details about the rationale.
* [`datacommons_client/models/node.py`](diffhunk://#diff-1816caba4b54e536065474e7e040883c0e23d27651b707995781b8458066fd9fR1-R113): Added `Node`, `NodeGroup`, `Arcs`, and `Properties` data classes to represent nodes, groups of nodes, arcs, and properties in the Data Commons knowledge graph. 
* [`datacommons_client/models/observation.py`](diffhunk://#diff-f1f665d269a5d622ebcb7cc1f5f3fdaaa7556e4a29f6523f3e33bede0e5136b5R1-R147): Added `Observation`, `OrderedFacets`, `Variable`, and `Facet` …
> Implement Data Classes to Model API Responses

- datacommons_client/client.py
- datacommons_client/endpoints/observation.py
- datacommons_client/endpoints/response.py
- datacommons_client/models/observation.py
- datacommons_client/tests/endpoints/test_response.py
- datacommons_client/tests/test_client.py
- datacommons_client/tests/test_decorators.py
- datacommons_client/utils/data_processing.py
- datacommons_client/utils/decorators.py
This PR introduces the`DataCommonsClient` class to interact with the Data Commons API, along with various utility functions and tests. 
The DataCommonsClient class would be the main entry point for most users. As described in the design doc:
> The datacommons entrypoint would coordinate interactions with and between classes. 
>It would simply provide convenient access to the different endpoints, centralising where the api_key and dc_instance are provided, and binding a specific ‘client’ instance to a specific knowledge graph and API key.
>It will also add convenient methods to perform additional, higher-level interactions with the data/api. For example, it can implement a method to get data as a nicely structured Pandas DataFrame (if the optional dependency is installed).
This …
> Add client class

- CHANGELOG.md
- cloudbuild.yaml
- datacommons_client/README.md
- datacommons_client/__init__.py
- datacommons_client/endpoints/node.py
- datacommons_client/endpoints/payloads.py
- datacommons_client/tests/endpoints/test_payloads.py
- datacommons_client/tests/endpoints/test_resolve_endpoint.py
- docs/development.md
- docs/release.md
- pyproject.toml
- run_test.sh
This PR focuses on improvements to the packaging process. It:
- Introduces a `pyproject.toml` file for PEP 518-compliant builds. This files mirrors the information included in the legacy packages `setup.py` files. Note that the minimum python version supported will be `3.10` given that `<3.8` reached their end of life last year, and `3.9` will reach its end of life later this year. We could in theory support `3.9` still - so let me know if I should change that. Also note that I've added one.org as authors and maintainers (in addition to the datacommons team of course).
- Introduces `hatch` as the primary tool for packaging and managing development dependencies. I tried to make its introduction as unobtrusive as possible. The main rationale was to improve and simplify the packaging …
> Upgrade packaging process for V2 beta release

- datacommons_client/client.py
- datacommons_client/tests/test_client.py
@kmoscoe identified an improvement we can make to how the `DataCommonsClient` class handles a fully resolved URL.
For context, during the design phase, @dwnoble requested having a way to provide a fully resolved URL, instead of the URL of Google's Data Commons (datacommons.org) or the URL of a custom Data Commons instance (like datacommons.one.org). 
That means that the `DataCommonsClient` class is initiated with:
```python
""" 
Args:
api_key (Optional[str]): The API key for authentication. Defaults to None. Note that
custom DC instances do not currently require an API key.
dc_instance (Optional[str]): The Data Commons instance to use. Defaults to "datacommons.org".
url (Optional[str]): A custom, fully resolved URL for the Data Commons API. Defaults to None.
"""
```
However, as @kmoscoe …
> Improve `url` handling

- datacommons_client/endpoints/node.py
There is no data() method on the NodeResponse.
> Fix some erroneous comments in node.py

- datacommons_client/endpoints/resolve.py
- datacommons_client/tests/endpoints/test_resolve_endpoint.py
With thanks to @kmoscoe for figuring this out.
This method is of extremely limited utility (or perhaps none). I had missed the fact that “the expression must end with ->dcid”. Which means it’s impossible to create correspondence dictionaries to anything but dcids.
If there’s no way for the REST API to convert a dcid to a different type (say a wikiID) then there’s no real value for this method. This PR removes it.
If the REST API were capable of resolving something other than dcids in the future, we could reimplement this. In the meantime, all of this functionality is covered (in a clearer way) by other methods.
> Remove `fetch_entity_type_correspondence`

- datacommons_client/client.py
- datacommons_client/endpoints/observation.py
- datacommons_client/endpoints/payloads.py
- datacommons_client/tests/endpoints/test_observation_endpoint.py
- datacommons_client/tests/endpoints/test_payloads.py
This PR adds support for the domains and facets filters for the Observations endpoint. These filters were recently documented by @kmoscoe.
The filters are implemented as additional parameters for the `ObservationEndpoint`:
```python
domains_filter: Optional[str | list[str]] = None
facets_filter: Optional[str | list[str]] = None
```
They are used when building the payload via the `ObservationRequestPayload`. The payload will add a "filter" key with the right contents if either `domains_filter` or `facets_filter` is used.
From a user point of view, this PR will enable this type of queries
```python
from datacommons_client import DataCommonsClient
dc = DataCommonsClient(dc_instance="datacommons.one.org")
response_with_facet_filter = dc.observation.fetch(
variable_dcids="Count_Person", …
```
> Add support for domain and facet filters

- datacommons_client/client.py
- datacommons_client/endpoints/observation.py
- datacommons_client/endpoints/payloads.py
- datacommons_client/endpoints/response.py
- datacommons_client/tests/endpoints/test_error_handling.py
- datacommons_client/tests/endpoints/test_observation_endpoint.py
- datacommons_client/tests/endpoints/test_payloads.py
- datacommons_client/tests/endpoints/test_response.py
- datacommons_client/tests/test_client.py
- datacommons_client/utils/error_handling.py
This is an exciting new feature, inspired by our recent work on supporting the Observation facet filters.
**TL;DR**
This PR makes it possible to specify property filters so that only the relevant observations are fetched. This could substantially reduce the amount of data transferred if users specify a particular `unit`, `measurementMethod`, `observationPeriod`, etc.
---
Sample usage:
```python
from datacommons_client import DataCommonsClient
dc = DataCommonsClient(dc_instance="datacommons.one.org")
df = dc.observations_dataframe(
variable_dcids=["Count_Person"],
date="all",
entity_dcids=["country/USA"],
property_filters={
"measurementMethod": ["CensusACS5yrSurvey", "OECDRegionalStatistics"]
},
)
```
The above will make a first call to the Observations endpoint to get the facets …
> feature: support property filters in `observations_dataframe` 

- datacommons_client/endpoints/node.py
- datacommons_client/tests/endpoints/test_node_endpoint.py
With thanks to @kmoscoe for spotting this. The API does not accept lists of expressions (it needs to start with an arrow which makes it impossible to ask for multiple properties this way, for example).
This PR fixes the `node.fetch` typehint since only strings (and not lists of strings) are accepted. It also removes a related test.
> Fix typehint

- datacommons_client/endpoints/resolve.py
- datacommons_client/endpoints/response.py
- datacommons_client/tests/endpoints/test_resolve_endpoint.py
Move the logic from a standalone `flatten_respolve_response` function, to a method of the Response object. That way it complements `to_dict`, `to_json` with `to_flat_dict`.
Example usage:
```python
from datacommons_client import DataCommonsClient
dc = DataCommonsClient(dc_instance="datacommons.one.org")
response = dc.resolve.fetch_dcids_by_name(
["Guatemala", "France", "Germany", "United States", "United Kingdom"],
entity_type="Country",
)
```
This would return a `ResolveResponse` object. 
Calling the regular `to_dict` would look like this, keeping the original response structure and nesting intact.
```python
response.to_dict()
{'entities': [{'candidates': [{'dcid': 'country/FRA'}, {'dcid': 'country/FXX'}],
'node': 'France'},
{'candidates': [{'dcid': 'country/DEU'}], 'node': 'Germany'}, …
```
> Refactor `flatten_resolve_response`

- datacommons_client/endpoints/resolve.py
- datacommons_client/tests/endpoints/test_resolve_endpoint.py
With thanks to @kmoscoe for spotting the naming inconsistency, this PR:
- Renames `.fetch_dcid_by_wikidata_id` to `fetch_dcids_by_wikidata_id` to clarify lists are accepted.
- Adds a test for lists of `wikidata_ids`
> `fetch_dcids_by_wikidata_id` improvement

- datacommons_client/endpoints/observation.py
- datacommons_client/tests/endpoints/test_observation_endpoint.py
- datacommons_client/tests/test_utils.py
- datacommons_client/utils/data_processing.py
This PR is part of a group of PRs which will bring some key features from the Data Commons website API to the client library (e.g #230, #231).
**Fetch available statistical variables**: this is an implementation of [this feature of the DC website](https://github.com/datacommonsorg/website/blob/master/server/lib/fetch.py#L344-L363).
In short, this PR:
- Adds a `fetch_available_statistical_variables` method to the ObservationEndpoint. This method fetches all statvars which have observations for one or more entities.
It also includes tests for the method and a helper function which structures the data by entity : statvar_list.
Example usage:
```python
from datacommons_client import DataCommonsClient
dc = DataCommonsClient(dc_instance="datacommons.one.org")
variables = …
```
> Add `fetch_available_statistical_variables`

- datacommons_client/endpoints/node.py
- datacommons_client/endpoints/response.py
- datacommons_client/models/base.py
- datacommons_client/models/node.py
- datacommons_client/tests/endpoints/test_node_endpoint.py
- datacommons_client/tests/test_names.py
- datacommons_client/utils/names.py
This PR is part of a group of PRs which will bring some key features from the Data Commons website API to the client library (e.g #229, #231)
**Fetch entity names**: this is an implementation of a few DC website features:
- The name endpoint of the [internal API](https://github.com/datacommonsorg/website/blob/master/server/routes/shared_api/place.py#L158-L171). `/api/place/name`
- The [internal code](https://github.com/datacommonsorg/website/blob/master/server/lib/shared.py#L22-L55) to fetch the english names from the `name` property.
- The [internal code](https://github.com/datacommonsorg/website/blob/master/server/routes/shared_api/place.py#L174-L213) to fetch the i18n name using the `nameWithLanguage` property (the website automatically resolves the user's locale, this method takes it …
> Add `fetch_entity_names` method

- datacommons_client/tests/endpoints/test_response.py
- datacommons_client/utils/data_processing.py
Fixes a bug caused when the arc does not contain `nodes`.  It was returning a `TypeError: 'NodeGroup' object is not subscriptable`.
With this PR the behaviour is consistent and an empty list is returned instead.
Also added a test for this specific case.
> bug: fix arc unpacking

- datacommons_client/client.py
- datacommons_client/endpoints/observation.py
- datacommons_client/endpoints/response.py
- datacommons_client/tests/endpoints/test_observation_endpoint.py
- datacommons_client/tests/endpoints/test_response.py
- datacommons_client/tests/test_client.py
This PR addresses feedback from @kmoscoe:
- [Removes](77340ff98460f5ea101beeac545ec4bb7c696443) `fetch_latest_observations` as it didn’t really serve a useful role
- [Removes](5717ca261232eed78a3c49c5dd0ff8c033c16245)`fetch_latest_observations_by_entity` as it is basically the same as `fetch_observations_by_entity` but just with a default of the latest date.
- [Renames](f042f67e57d36b015be80a16c0e792f31fac92aa) `fetch_observations_by_entity` to `fetch_observations_by_entity_dcid`
- [Renames](bfa3f5978618ac845f10a84625cc12f90c42542e) `get_observations_as_records` to `to_observation_records`. This name more accurately reflects what the method does: it transforms nested observation data and facet metadata into a list of flat, record-like dictionaries suitable for analysis. This mirrors …
> Improvements suggested by kara

- datacommons_client/tests/endpoints/test_response.py
- datacommons_client/utils/data_processing.py
Also adds more explicit arg types for `unpack_arcs` and `flatten_properties`.
> Fix unpack_arcs when multiple arcs are in the node response

- datacommons_client/endpoints/node.py
- datacommons_client/tests/endpoints/test_node_endpoint.py
- datacommons_client/tests/utils/test_graph.py
- datacommons_client/utils/graph.py
TL;DR: This PR refactors the ascendency features in order to work for children/descendants as well.
This creates convenient ways to fetch parents and children of given entities. This can be done for the immediate cases, or recursively up and down the graph.
`fetch_entity_children` takes one or more entity dcids and fetches its children via the `containedInPlace`. It optionally accepts `children_type` which gets only children of a specific type (e.g., 'Country', 'State', 'IPCCPlace_50')
`fetch_entity_descendancy` is a similar method, but it does so via BFS recursively. It is highly recommended to specify a type in that case, as otherwise the search can become extremely large for entities further up in the graph.
This PR was inspired by #238 by @clincoln8, though it does not address the …
> Add children / descendants methods 

- datacommons_client/utils/data_processing.py
TL;DR: the REST API can return valid but malformed responses with empty data. This small fix defends against that when flattening the response.
Thanks @kmoscoe for spotting this!
---
A typical node response looks as follows:
```json
{
"data": {
"geoId/15009991200": {
"arcs": {
"containedInPlace": {
"nodes": [
{
"dcid": "geoId/150099912000",
"name": "Block Group 0, Census Tract 9912, Maui County, Hawaii",
"provenanceId": "dc/base/BaseGeos",
"types": [
"CensusBlockGroup"
]
}
]
}
}
}
}
}
```
However, for some *obscure* nodes, the response unexpectedly structured as:
```json
{
"data": {
"dc/2d5th8wq69trh": {}
}
}
```
This is a REST API issue. I will submit a bug about it.
This PR makes sure that when extracting properties we can deal with this type of empty response.
> [Fix] Handle empty/malformed REST API node responses

- datacommons_client/endpoints/node.py
This PR handles deprecated methods in the `NodeEndpoint` class. These methods are deprecated because they were renamed in an effort to make them more user-friendly.
I've implemented deprecation via a module-level mapper, in case this happens again in the future and to have clear visibility over deprecated or renamed methods - for when they are eventually fully removed. This mapper is used by a dynamic attribute handler to warn about and redirect deprecated method calls, and ensuring backward compatibility, including for updated argument names.
* `_DEPRECATED_METHODS` maps deprecated method names to their new names and argument mappings.
* A new `__getattr__` method in the `NodeEndpoint` class intercepts calls to deprecated methods, issues deprecation warnings, and redirects to the new …
> [Node] Make renamed methods backwards compatible

- datacommons_client/utils/dataframes.py
Using pd.DataFrame as a type hint causes a `AttributeError: 'NoneType' object has no attribute 'DataFrame'` exception when pandas is not installed because pd.Dataframe evaluates to None.DataFrame.
The comments `# type: ignore[reportInvalidTypeForm]` is to ignore VSCode Pylance warning of "Variable not allowed in type expression [Pylance(reportInvalidTypeForm)]" since pd is instantiated as a variable when pandas is not installed. 
Testing Approach:
1. (Before) From the the root of the repo in a python env _without pandas installed,_ I ran:
```
python3 -m pip install .
python3 datacommons_client/utils/dataframes.py
```
This raised:
```
Traceback (most recent call last):
File "/Users/calinc/api-python/datacommons_client/utils/dataframes.py", line 1, in <module>
from …
```
> Use string literal type hints for pd.DataFrame.

- datacommons_client/client.py
- datacommons_client/endpoints/node.py
- datacommons_client/models/node.py
- datacommons_client/tests/endpoints/test_node_endpoint.py
- datacommons_client/tests/models/test_node_models.py
- datacommons_client/tests/test_client.py
- datacommons_client/tests/test_dataframes.py
- datacommons_client/utils/dataframes.py
This PR adds support for including property constraint metadata for statistical variables in observation DataFrames. To support this, it includes new models and endpoint methods to fetch and represent these constraints. The PR also includes tests for all new functionality.
In short:
* Added new pydantic models `StatVarConstraint` and `StatVarConstraints` to represent constraints associated with statistical variables.
* Implemented `NodeEndpoint.fetch_statvar_constraints` to fetch and structure constraint property/value pairs for a set of  statvars.
* Updated `Client.observations_dataframe` to support an `include_constraints_metadata` argument; when enabled, the returned DataFrame includes constraint id/name columns for each variable.
* Added utility function …
> Optionally include constraint property metadata in observation DataFrames
